export interface CriticalResult {
	range: [number, number];
	effect: string;
}

export interface CriticalTables {
	[key: string]: CriticalResult[];
}

const criticalTables: CriticalTables = {
	Crush: [
		{ range: [-49, 5], effect: 'Weak grip. No extra damage. +0 hits.' },
		{ range: [6, 20], effect: 'Minor fracture of ribs. +5 hits. -5 to activity.' },
		{ range: [21, 35], effect: 'Blow to side. +4 hits. -40 to activity for 1 round.' },
		{ range: [36, 50], effect: 'Blow to forearm. +5 hits. If no arm armor, stunned 1 round.' },
		{ range: [51, 65], effect: 'Blow to shield arm. +5 hits. If no shield: shoulder snaps. Arm useless.' },
		{ range: [66, 79], effect: 'Blow breaks bone in leg. +12 hits. -60 to activity. Stunned 3 rounds.' },
		{ range: [80, 80], effect: 'Strike to forehead. +30 hits. One eye destroyed. Stunned 24 rnds. If no helm: -1 month coma results.' },
		{ range: [81, 86], effect: 'Blow to weapon arm. +8 hits. Shield 2 rounds. If no arm armor: tendon damaged, arm broken and useless.' },
		{ range: [87, 89], effect: 'Shatter knee. +9 hits. -60 to activity. Knocked down and stunned for 3 rounds.' },
		{ range: [90, 90], effect: 'Blow to back of neck paralyzes foe: the shoulders down. +24 hits. Foe quite stunned.' },
		{ range: [91, 96], effect: 'Unconscious for 4 hours due to blow to side of head. If no helm: skull crushed. +20 hits.' },
		{ range: [97, 99], effect: 'Strike to side of head. Foe in cage through lungs. Drops and dies in 6 rounds.' },
		{ range: [100, 100], effect: 'Blow to jaw. Drives bone into brain. Dies instantly.' },
		{ range: [101, 106], effect: 'Blow breaks hip. +15 hits. -75 to activity. Knocked down and stunned 3 rounds.' },
		{ range: [107, 109], effect: 'Strike to side of head. Foe cannot breath and stunned for 12 rounds. Dies in 9 rounds.' },
		{ range: [110, 110], effect: 'Crushed hip. +35 hits. Stunned 12 rounds. Active the following 4 rounds then dies of nerve failure.' },
		{ range: [111, 116], effect: 'Shatter elbow in weapon arm. Arm useless. Stunned 5 rounds.' },
		{ range: [117, 119], effect: 'Blow to side crushes chest cavity. +10 hits and dies in 3 rounds.' },
		{ range: [120, 120], effect: 'Blow to chest area. Destroys heart. Die immediately. +25 hits. Enjoy soon.' }
	],
	Slash: [
		{ range: [-49, 5], effect: 'Weak strike yields no extra damage. +0 hits.' },
		{ range: [6, 20], effect: 'Minor calf wound. 1 hit per round' },
		{ range: [21, 35], effect: 'Blow to upper leg. +5 hits. If no leg armor: stunned 1 round.' },
		{ range: [36, 50], effect: 'Minor chest wound. +3 hits. 1 hit per round. -5 to activity' },
		{ range: [51, 65], effect: 'Minor forearm wound. +4 hits. 2 hits per round. Stunned 1 round.' },
		{ range: [66, 79], effect: 'Medium thigh wound. +6 hits. 1 hit per round. 10 to activity. Stunned 2 rounds.' },
		{ range: [80, 80], effect: 'Neck strike severs carotid artery. Neck broken. Dies in 1 round of intense agony.' },
		{ range: [81, 86], effect: 'Slash weapon arm. +10 hits. 1 hit per round. If no arm armor: muscle and tendon damage, arm useless.' },
		{ range: [87, 89], effect: 'Destroys one eye. +10 hits. Stunned for 30 rounds.' },
		{ range: [90, 90], effect: 'Disemboweled, dies instantly. 25% chance your weapon is stuck in opponent for 2 rounds.' },
		{ range: [91, 96], effect: 'Knocked out for 6 hours with a strike to side of head. +15 hits. If no helm: dies instantly.' },
		{ range: [97, 99], effect: 'Severs lower leg. 20 hits round. Drops and lapses into unconsciousness.' },
		{ range: [100, 100], effect: 'Slash side. Down, unconscious and dies in 3 rounds due to massive internal organ damage.' },
		{ range: [101, 106], effect: 'Major abdominal wound. +10 hits. 8 hits per round. -10 to activity. Stunned for 4 rounds.' },
		{ range: [107, 109], effect: 'Severs weapon arm. 15 hits per round. Down and unconscious in 3 rounds immediately.' },
		{ range: [110, 110], effect: 'Impaled in heart. Dies instantly. Heart destroyed. 25% chance your weapon is stuck in opponent for 4 rounds.' },
		{ range: [111, 116], effect: 'Sever hand. 12 hits per round. Knocked down and stunned for 6 rounds.' },
		{ range: [117, 119], effect: 'Sever spine. Collapses immediately. Paralyzed from the neck down permanently. +20 hits.' },
		{ range: [120, 120], effect: 'Strike to head destroys brain. Life is saved for the unfortunate fool. Expires in a heap, immediately.' }
	],
	Puncture: [
		{ range: [-49, 5], effect: 'Glancing blow. No extra damage.' },
		{ range: [6, 20], effect: 'Thigh strike. Blow to the side. +3 hits.' },
		{ range: [21, 35], effect: 'Thigh strike. +3 hits. If no leg armor: stunned 1 round.' },
		{ range: [36, 50], effect: 'Minor forearm wound. +2 hits. If no arm armor: stunned 1 round.' },
		{ range: [51, 65], effect: 'Strike above the collar bone per round. Stunned 1 round.' },
		{ range: [66, 79], effect: 'Strike to lower leg. Tendons torn. +3 hits. -25 to activity. Stunned 1 round.' },
		{ range: [80, 80], effect: 'Strike to neck. Nerves and blood vessels severed. Dies of a massive haemorrhage.' },
		{ range: [81, 86], effect: 'Strike to weapon arm. +10 hits. If no arm armor: bone broken, stunned 3 rounds.' },
		{ range: [87, 89], effect: 'Strike through lower leg. Sever muscle. -50 to activity. Stunned 3 rounds.' },
		{ range: [90, 90], effect: 'Strike through both lungs. Drops and passes out. Dies in 6 rounds.' },
		{ range: [91, 96], effect: 'Strike to side of head. Knocked out for 6 hours. +10 hits. If no helm: dies instantly.' },
		{ range: [97, 99], effect: 'Strike through neck breaks backbone and severs spine. Paralyzed from the neck down, permanently.' },
		{ range: [100, 100], effect: 'Strike through eye. Dies instantly. A real eye full.' },
		{ range: [101, 106], effect: 'Major abdominal wound. +10 hits. 6 hits per round. -20 to activity. Stunned 4 rounds.' },
		{ range: [107, 109], effect: 'Sever weapon arm. 15 hits per round. Down and unconscious. Dies from internal bleeding and shock in 6 rounds.' },
		{ range: [110, 110], effect: 'Shot through heart. Reds 10 feet before dying. Weapon stuck in opponent. Victim dies 3 rounds.' },
		{ range: [111, 116], effect: 'Strike through leg. Artery severed. Knocked down and stunned. 12 hits per round.' },
		{ range: [117, 119], effect: 'Strike through kidneys. +9 hits. Knocked down and dies after 6 rounds of very intense agony. Sad.' },
		{ range: [120, 120], effect: 'Shot through both ears. Hearing impaired. Incurably. Awesome shot.' }
	],
	Unbalancing: [
		{ range: [-49, 5], effect: 'Fairly weak. +0 hits. Zip.' },
		{ range: [6, 20], effect: 'Arm strike. +2 hits. -5 to activity for 2 rounds.' },
		{ range: [21, 35], effect: 'Leg strike. +4 hits. If no leg armor: stunned 1 round.' },
		{ range: [36, 50], effect: 'Chest strike. Knocked back 3 feet. +5 hits. -10 to activity for 2 rnds.' },
		{ range: [51, 65], effect: 'Blow to shield arm. +5 hits.' },
		{ range: [66, 79], effect: 'Elbow strike. Forearm numbed. +8 hits. Drop weapon. -10 to activity for 10 rounds.' },
		{ range: [80, 80], effect: 'Brutal hip strike. Knocked down. Tendon torn and joint shattered Leg useless. -80 to activity.' },
		{ range: [81, 86], effect: 'Shot to side. Knocked 5 feet sideways. Drops anything carried in hands. Stunned 3 rounds.' },
		{ range: [87, 89], effect: 'Side strike. Stumble ungracefully to an embarrassing prone position. Stunned 6 rounds.' },
		{ range: [90, 90], effect: 'Back strike. Knocked flying 10\' onto face. Severe nerve damage. Paralyzed from waist down.' },
		{ range: [91, 96], effect: 'Hard head strike. Knocked back 10\' and stunned 6 rounds. If no helm: unconscious for 24 hours.' },
		{ range: [97, 99], effect: 'Totally awesome strike. Knocked to knees. If using 1 hand weapon: it is thrown back 20 feet. 10 feet. Stunned 15 rounds.' },
		{ range: [100, 100], effect: 'Upper chest struck. Knocked 10\' sideways. Fall down, break both arms. A 2 month coma results.' },
		{ range: [101, 106], effect: 'Blow breaks leg. +12 hits. -50 to activity. Stunned 3 rounds.' },
		{ range: [107, 109], effect: 'Strike to chest. Knocked 10\' back. +9 hits. Stunned 6 rounds. If no helm: 4 weeks coma.' },
		{ range: [110, 110], effect: 'Savage blow to head. Knocked down. Dies in 12 rounds due to severed vein.' },
		{ range: [111, 116], effect: 'Great side shot. Knocked down and sideways 5\'. Lower leg broken. Stunned 7 rounds. -40 to activity.' },
		{ range: [117, 119], effect: 'Blow to shield shoulder. Stunned 9 rounds. -20 to activity. If no shield: unconscious and upper arm shattered.' },
		{ range: [120, 120], effect: 'Frightening strike to temple. Knocked back 20 feet. Dies instantly. Not nice.' }
	],
	Grappling: [
		{ range: [-49, 5], effect: 'An opportunity lost.' },
		{ range: [6, 20], effect: 'Passing strike. +2 hits.' },
		{ range: [21, 35], effect: 'Attack fended off. +3 hits. If arm armor stunned 1 round.' },
		{ range: [36, 50], effect: 'Leg attack. Spun about, but breaks loose. If leg armor, stunned 1 round.' },
		{ range: [51, 65], effect: 'Shield arm entangled. If shield: -50 to activity until it is dropped. If no shield: -50 to activity for the weapon arm.' },
		{ range: [66, 79], effect: 'Weapon arm grasped. Disarmed and wrist grasped. Disarmed and stunned 2 rounds. -25 to activity.' },
		{ range: [80, 80], effect: 'Both legs entangled. Down and knocked out. +9 hits.' },
		{ range: [81, 86], effect: 'Weapon arm grappled. Ligaments torn and muscle damaged. Disarmed and stunned 3 rounds. -40 to activity.' },
		{ range: [87, 89], effect: 'Completely entangled and immobilized. Knocked down, but still conscious. No attack.' },
		{ range: [90, 90], effect: 'Vicious hold around neck. Knocked out. Sprained neck. -60 to activity.' },
		{ range: [91, 96], effect: 'Head grappled. Stunned 9 rounds. If no helm: a coma (1-10 days) results due to a fractured skull.' },
		{ range: [97, 99], effect: 'Both arms entangled and pinned to chest. Arms may not be moved until entanglement removed. -75 to activity.' },
		{ range: [100, 100], effect: 'Neck grappled. If neck armor: -60 to activity due to neck sprain and stunned 3 rounds. If not: broken neck.' },
		{ range: [101, 106], effect: 'Chest grasped. Ribs broken. Stunned 5 rounds. -10 to activity.' },
		{ range: [107, 109], effect: 'Legs entangled and completely immobilized. Fall and break weapon arm. Disarmed and knocked out. +20 hits.' },
		{ range: [110, 110], effect: 'Neck grappled. If neck armor: disarmed and stunned 5 rounds. If not: dies in 6 rounds.' },
		{ range: [111, 116], effect: 'Foot entangled. Stumble, fall, break weapon on impact, and stunned 2 rounds. If no chest armor: take a "D" crush crit.' },
		{ range: [117, 119], effect: 'Both legs wrapped up. Tumbles to ground and knocked out. -80 to activity due to a broken arm and a broken ankle. +20 hits.' },
		{ range: [120, 120], effect: 'Windpipe crushed. Dies instantly due to massive shock and savage asphyxiation.' }
	],
	Heat: [
		{ range: [-49, 5], effect: 'Hot air. +0 hits.' },
		{ range: [6, 20], effect: 'Strong heat, little effect. +3 hits.' },
		{ range: [21, 35], effect: 'Minor burns. +8 hits. 1 hit per round.' },
		{ range: [36, 50], effect: 'Blinded by hot smoke. +12 hits. Stunned 1 round.' },
		{ range: [51, 65], effect: 'Clothing catches on fire. Takes 2 rnds to extinguish. +12 hits. 8 hits per rnd after. Stunned 2 rnd. Knocked down by fiery blast. Any organic foot and calf covering destroyed. +10 hits.' },
		{ range: [66, 79], effect: 'Blast to head. Face horribly scarred. Knocked out. +15 hits. 5 hits per round. If no helm: 1 month coma results.' },
		{ range: [80, 80], effect: 'Fire engulfs back. Knocked down. All organic material on back destroyed. 2 hits per round. Stunned 1 round.' },
		{ range: [81, 86], effect: 'Strike to head. Blinded for 3 rounds. Any organic head covering destroyed. If no helm: 1 month coma.' },
		{ range: [87, 89], effect: 'Head becomes a charred stump. Sadly, dies instantly due to his unacceptable condition.' },
		{ range: [90, 90], effect: 'Shield arm fried. Any shield is destroyed along with hand. Stunned 5 rounds. If no shield: loses arm and knocked out.' },
		{ range: [91, 96], effect: 'Upper body charred. Dies at last due to tissue destruction. 2 hits per round. -60 to activity. Stunned for 6 rounds.' },
		{ range: [97, 99], effect: 'Blast of fire fuses vertebrae and unites skin with clothing. Paralyzed permanently. +25 hits.' },
		{ range: [100, 100], effect: 'Blast to leg. 2 hits/round. -20 to activity. If metal leg covering: massive tissue damage. -70 to activity.' },
		{ range: [101, 106], effect: 'Head strike. If any head covering: catch fire. Dies in 2 weeks. If not: dies in 6 rnds due to unsealed brain.' },
		{ range: [107, 109], effect: 'Midsection vaporized. Cut in half with blast. Clothing, armor, and all internal destroyed.' },
		{ range: [110, 110], effect: 'Blast to chest. Any chest armor is burned. +12 hits. Stunned 5 rounds. If no chest armor: knocked down, armor take a "D" crush crit.' },
		{ range: [111, 116], effect: 'Fire engulfs body. All organic material on body destroyed. Dies in 3 rounds. Nerve damage in 6 rnds. +25 hits.' },
		{ range: [117, 119], effect: 'All that remains are charred bits of real bone.' },
		{ range: [120, 120], effect: 'All that remains are charred bits of real bone.' }
	],
	Cold: [
		{ range: [-49, 5], effect: 'Cool breeze. +0 hits.' },
		{ range: [6, 20], effect: 'Cold blast. +3 hits. If no cloak or armor: stunned and stunned 1 rnd.' },
		{ range: [21, 35], effect: 'Frosty "burn." +7 hits. 1 hit per round' },
		{ range: [36, 50], effect: 'Mild frostbite. +5 hits. 2 hits per round and -10 to activity.' },
		{ range: [51, 65], effect: 'Back strike. +9 hits. 2 hits/rnd. Stunned 2 rnds. Wood exposed on back is now. Frozen solid.' },
		{ range: [66, 79], effect: 'Strong, but low, blast. Stunned 1 round. If no foot covering: frostbite, -30 to activity destroyed. If no foot covering: frostbite. -30 to activity.' },
		{ range: [80, 80], effect: 'Icy blast to head. A mouth long icicle (and he sold) results. Loses nose as a result of severe frostbite and shock.' },
		{ range: [81, 86], effect: 'Strike to leg. Knocked down. Stunned 3 rounds. If no leg armor: frostbite, lower leg useless and -50 to activity.' },
		{ range: [87, 89], effect: 'Strike to neck and collar area. Knocked out. Lose voice results. If no neck armor: neck is frozen and dies in 3 rounds of massive shock.' },
		{ range: [90, 90], effect: 'Blast freeze-dries head. Dies in 2 rounds. Cold to death, at least his torso is not brittle and lifeless.' },
		{ range: [91, 96], effect: 'Thigh strike. Icicles bone and frostbite. 5 hits per round. -30 to activity. Stunned 4 rounds.' },
		{ range: [97, 99], effect: 'Side strike freezes and shatters pelvis. Dies in 12 rounds due to severe internal organ damage. Stunned for 6 rounds.' },
		{ range: [100, 100], effect: 'Head strike. Eyes are frozen. A 3 week coma results. Paralyzed from the neck.' },
		{ range: [101, 106], effect: 'Blast freezes both hands. Loses use of both. If no hand armor: 1 hit per round. Stunned for 5 rounds.' },
		{ range: [107, 109], effect: 'Head strike. If head covering: frozen. Dies in 6 inactive rounds. If not: skull and suffocates.' },
		{ range: [110, 110], effect: 'Massive strike shatters chest and freezes precious bodily fluids. Dies in 3 rounds.' },
		{ range: [111, 116], effect: 'Icy blast to upper chest. Knocked down. Lungs freeze. Suffers dies in 10 rounds due to a cold, cold heart.' },
		{ range: [117, 119], effect: 'Frozen into a lifeless statue— first preserve him, and paint him pretty to last so long. Awesome.' },
		{ range: [120, 120], effect: 'Frozen solid, then shatters into thousands of pieces after being knocked into the ground.' }
	],
	Electricity: [
		{ range: [-49, 5], effect: 'Hair stands up. +0 hits.' },
		{ range: [6, 20], effect: 'Light charge. +3 hits. If metal armor: stunned 1 rounds.' },
		{ range: [21, 35], effect: 'Explosion of light. Stunned 1 round.' },
		{ range: [36, 50], effect: 'Medium charge. +6 hits. -5 to activity. If metal armor: stunned 2 rounds.' },
		{ range: [51, 65], effect: 'Heavy charge. +9 hits. -10 to activity. Stunned 1 round. If metal armor: stunned 2 rounds.' },
		{ range: [66, 79], effect: 'Strike to shield arm. +12 hits. -20 to activity. If metal armor and no shield: knocked out for 1 day.' },
		{ range: [80, 80], effect: 'Strike to side devastates nervous system. Severe shock results. Victim is a living vegetable for 1 month.' },
		{ range: [81, 86], effect: 'Strike to weapon arm. 2 hits per round. If no leather protection: muscle and cartilage mangled, arm useless, stunned for 3 rounds.' },
		{ range: [87, 89], effect: 'Permeated by electricity. Entire nervous system rearranged. Drops and lies in shock for 12 rounds before dying.' },
		{ range: [90, 90], effect: 'Head strike. If leather helm: it is destroyed. 2 week coma results. If not: dies instantly as brain is fried.' },
		{ range: [91, 96], effect: 'Chest strike. If metal armor: it becomes fused and immobile. If not: knocked out for 6 hours.' },
		{ range: [97, 99], effect: 'Electrifying experience. Brain falls victim to massive shock and surface burns inside and dies in 6 rounds.' },
		{ range: [100, 100], effect: 'Nervous system acts as a superconductor. Instant death provided foe is in agony, did slow. A 3 week coma results. Paralyzed from the neck.' },
		{ range: [101, 106], effect: 'Strike to face. Loses nose. Stunned 4 rounds. If metal face plate: If no helm: knocked down as well.' },
		{ range: [107, 109], effect: 'Blow to side. Bone is driven into kidneys. Dies in 6 rounds.' },
		{ range: [110, 110], effect: 'Disrupt chest. Lungs and heart explode from impact. Dies instantly. Very messy.' },
		{ range: [111, 116], effect: 'Spun by blow. Knocked down. Breaks both arms. If no activity. Stunned 5 rounds.' },
		{ range: [117, 119], effect: 'Blast shatters skull into thousands of particles. Dies instantly. Direct hit, no punch.' },
		{ range: [120, 120], effect: 'Blast annihilates entire skeleton. Reduced to a gelatinous pulp. Try a spatula.' }
	],
	Impact: [
		{ range: [-49, 5], effect: 'Not even a scratch. +0 hits.' },
		{ range: [6, 20], effect: 'Grazing shot. +5 hits.' },
		{ range: [21, 35], effect: 'Staggered by strike to side. +10 hits. Stunned 1 round.' },
		{ range: [36, 50], effect: 'Strike to shoulder. Spun about. Reel backwards 10 feet. +12 hits. If no armor: stunned 2 rounds.' },
		{ range: [51, 65], effect: 'Strike to leg. Knocked down. +8 hits. If no leg armor: stunned 2 rounds.' },
		{ range: [66, 79], effect: 'Blast to shield arm. +10 hits. Shield or arm armor destroyed. If none: arm broken and useless, stunned 3 rounds.' },
		{ range: [80, 80], effect: 'Strike to head. +12 hits. Helm is shattered. Knocked down and out for 1 day. If no helm: skull fractured, dies in 3 rounds.' },
		{ range: [81, 86], effect: 'Blow to upper leg. Muscles torn. +15 hits. -10 to activity. If no leg armor: -20 to activity and stunned 3 rounds.' },
		{ range: [87, 89], effect: 'Blast to collar area. +12 hits. Stunned 5 rounds. Broken collar bone. If no helm: voice loss is permanent.' },
		{ range: [90, 90], effect: 'Blast to head. +20 hits. Paralyzed from the shoulders down. A melancholy mood falls on victim.' },
		{ range: [91, 96], effect: 'Blow to knee. Knee dislocated. Cartilage and tendons ripped. +15 hits. -50 to activity. Stunned 9 rounds.' },
		{ range: [97, 99], effect: 'Strike abdomen. +18 hits. Stunned 12 rounds. If no abdomen armor: dies in 6 rounds due to destroyed organs.' },
		{ range: [100, 100], effect: 'Blast to head disintegrates helm. A 3 week coma results. If no helm: dies immediately.' },
		{ range: [101, 106], effect: 'Blow to jaw. Jaw broken. Cannot speak or eat solid food until healed. +15 hits. Stunned 7 rnds.' },
		{ range: [107, 109], effect: 'Blow to side. Bone is driven into kidneys. Dies in 6 rounds.' },
		{ range: [110, 110], effect: 'Disrupt chest. Lungs and heart explode from impact. Dies instantly. Very messy.' },
		{ range: [111, 116], effect: 'Spun by blow. Knocked down. Breaks both arms. If no activity. Stunned 5 rounds.' },
		{ range: [117, 119], effect: 'Blast shatters skull into thousands of particles. Dies instantly. Direct hit, no punch.' },
		{ range: [120, 120], effect: 'Blast annihilates entire skeleton. Reduced to a gelatinous pulp. Try a spatula.' }
	]
};

export default criticalTables;