export interface Weapon {
	id: string;
	category?: string;
	name: string;
	iconUrl?: string;
	fumbleRange?: string;
	primaryCritical?: string;
	secondaryCritical?: string;
	baseRange?: string;
	weightLb?: number | string;
	notes?: string;
}

const weapons: Weapon[] = [
	// 1-Handed Edged (can be used with a shield)
	{
		id: 'broadsword',
		category: '1-Handed Edged',
		name: 'Broadsword',
		iconUrl: 'https://api.iconify.design/mdi:sword.svg',
		fumbleRange: '1-3',
		primaryCritical: 'Slash',
		secondaryCritical: '—',
		baseRange: '—',
		weightLb: 4,
		notes: 'can be used with a shield',
	},
	{
		id: 'dagger',
		category: '1-Handed Edged',
		name: 'Dagger',
		iconUrl: 'https://api.iconify.design/mdi:knife.svg',
		fumbleRange: '1',
		primaryCritical: 'Puncture(C)',
		secondaryCritical: '—',
		baseRange: '15',
		weightLb: '—',
		notes: 'can be used with a shield',
	},
	{
		id: 'handaxe',
		category: '1-Handed Edged',
		name: 'Handaxe',
		iconUrl: 'https://api.iconify.design/mdi:axe.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Slash',
		secondaryCritical: '—',
		baseRange: '15',
		weightLb: 5,
		notes: '+5 OB against chain & plate',
	},
	{
		id: 'scimitar',
		category: '1-Handed Edged',
		name: 'Scimitar',
		iconUrl: 'https://api.iconify.design/mdi:sword.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Slash',
		secondaryCritical: '—',
		baseRange: '—',
		weightLb: 4,
		notes: '-5 OB (chain/plate), +5 OB (other)',
	},
	{
		id: 'shortsword',
		category: '1-Handed Edged',
		name: 'Short Sword',
		iconUrl: 'https://api.iconify.design/mdi:sword.svg',
		fumbleRange: '1-2',
		primaryCritical: 'Slash',
		secondaryCritical: '—',
		baseRange: '3',
		weightLb: 3,
		notes: '-10 OB (chain/plate), +10 OB (other)',
	},

	// 1-Handed Concussion (can be used with a shield)
	{
		id: 'club',
		category: '1-Handed Concussion',
		name: 'Club',
		iconUrl: 'https://api.iconify.design/mdi:hammer.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Crush(D)',
		secondaryCritical: '—',
		baseRange: '2',
		weightLb: 5,
		notes: '-10 OB',
	},
	{
		id: 'mace',
		category: '1-Handed Concussion',
		name: 'Mace',
		iconUrl: 'https://api.iconify.design/mdi:hammer.svg',
		fumbleRange: '1-2',
		primaryCritical: 'Crush',
		secondaryCritical: '—',
		baseRange: '5',
		weightLb: 5,
		notes: '—',
	},
	{
		id: 'morningstar',
		category: '1-Handed Concussion',
		name: 'Morning Star',
		iconUrl: 'https://api.iconify.design/mdi:hammer.svg',
		fumbleRange: '1-8',
		primaryCritical: 'Crush',
		secondaryCritical: 'Puncture(A)',
		baseRange: '—',
		weightLb: 6,
		notes: '+10 OB, take B critical if fumbled',
	},
	{
		id: 'net',
		category: '1-Handed Concussion',
		name: 'Net',
		iconUrl: 'https://api.iconify.design/mdi:net.svg',
		fumbleRange: '1-6',
		primaryCritical: 'Grapple',
		secondaryCritical: '—',
		baseRange: '10',
		weightLb: 3,
		notes: '+15 OB',
	},
	{
		id: 'warhammer',
		category: '1-Handed Concussion',
		name: 'War Hammer',
		iconUrl: 'https://api.iconify.design/mdi:hammer.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Crush',
		secondaryCritical: '—',
		baseRange: '10',
		weightLb: 5,
		notes: '+5 OB (chain/plate), -10 OB (other)',
	},
	{
		id: 'whip',
		category: '1-Handed Concussion',
		name: 'Whip',
		iconUrl: 'https://api.iconify.design/mdi:whip.svg',
		fumbleRange: '1-6',
		primaryCritical: 'Grapple(C)',
		secondaryCritical: 'Slash(A)',
		baseRange: '3',
		weightLb: '—',
		notes: '-10 OB, can use from 2nd line',
	},

	// 1-Handed Pole Arms (can be used with a shield or 2-Handed with +10 to OB)
	{
		id: 'javelin',
		category: '1-Handed Pole Arms',
		name: 'Javelin',
		iconUrl: 'https://api.iconify.design/mdi:spear.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Puncture',
		secondaryCritical: '—',
		baseRange: '30',
		weightLb: 4,
		notes: '-10 OB, can use from 2nd line',
	},
	{
		id: 'spear',
		category: '1-Handed Pole Arms',
		name: 'Spear',
		iconUrl: 'https://api.iconify.design/mdi:spear.svg',
		fumbleRange: '1-5',
		primaryCritical: 'Puncture',
		secondaryCritical: 'Slash(A)',
		baseRange: '20',
		weightLb: 5,
		notes: '-5 OB, can use from 2nd line',
	},

	// 2-Handed Pole Arms (require both hands to use)
	{
		id: 'mounted_lance',
		category: '2-Handed Pole Arms',
		name: 'Mounted Lance',
		iconUrl: 'https://api.iconify.design/mdi:spear.svg',
		fumbleRange: '1-7',
		primaryCritical: 'Puncture',
		secondaryCritical: 'Unbalance',
		baseRange: '10',
		weightLb: 15,
		notes: '+15 OB, take B critical if fumbled',
	},
	{
		id: 'halbard',
		category: '2-Handed Pole Arms',
		name: 'Halbard',
		iconUrl: 'https://api.iconify.design/mdi:halberd.svg',
		fumbleRange: '1-7',
		primaryCritical: 'Slash',
		secondaryCritical: 'Puncture',
		baseRange: '—',
		weightLb: 7,
		notes: '-5 OB, can use from 2nd line',
	},

	// 2-Handed Weapons (cannot be used with a shield)
	{
		id: 'battle-axe',
		category: '2-Handed Weapons',
		name: 'Battle-axe',
		iconUrl: 'https://api.iconify.design/mdi:axe-battle.svg',
		fumbleRange: '1-5',
		primaryCritical: 'Slash',
		secondaryCritical: 'Crush',
		baseRange: '—',
		weightLb: 7,
		notes: '+5 OB (chain/plate), -5 (other)',
	},
	{
		id: 'flail',
		category: '2-Handed Weapons',
		name: 'Flail',
		iconUrl: 'https://api.iconify.design/mdi:chain.svg',
		fumbleRange: '1-8',
		primaryCritical: 'Crush',
		secondaryCritical: 'Puncture',
		baseRange: '—',
		weightLb: 7,
		notes: '+10 OB, take C critical if fumbled',
	},
	{
		id: 'quarterstaff',
		category: '2-Handed Weapons',
		name: 'Quarterstaff',
		iconUrl: 'https://api.iconify.design/mdi:staff.svg',
		fumbleRange: '1-3',
		primaryCritical: 'Crush',
		secondaryCritical: '—',
		baseRange: '—',
		weightLb: 4,
		notes: '-10 OB',
	},
	{
		id: 'two-handed-sword',
		category: '2-Handed Weapons',
		name: '2-Handed Sword',
		iconUrl: 'https://api.iconify.design/mdi:sword.svg',
		fumbleRange: '1-5',
		primaryCritical: 'Slash',
		secondaryCritical: 'Crush',
		baseRange: '—',
		weightLb: 8,
		notes: '—',
	},

	// Missile Weapons (may not be used in melee)
	{
		id: 'bola',
		category: 'Missile Weapons',
		name: 'Bola',
		iconUrl: 'https://api.iconify.design/mdi:net.svg',
		fumbleRange: '1-7',
		primaryCritical: 'Grapple',
		secondaryCritical: 'Crush(A)',
		baseRange: '40',
		weightLb: 3,
		notes: '-5 OB, take B critical if fumbled',
	},
	{
		id: 'composite_bow',
		category: 'Missile Weapons',
		name: 'Composite Bow',
		iconUrl: 'https://api.iconify.design/mdi:bow-arrow.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Puncture',
		secondaryCritical: '—',
		baseRange: '75*',
		weightLb: 3,
		notes: 'Load(1), or Reload(O) at -25 to OB',
	},
	{
		id: 'crossbow',
		category: 'Missile Weapons',
		name: 'Crossbow',
		iconUrl: 'https://api.iconify.design/mdi:crossbow.svg',
		fumbleRange: '1-5',
		primaryCritical: 'Puncture',
		secondaryCritical: '—',
		baseRange: '90',
		weightLb: 8,
		notes: 'Load(2), +20 OB at up to 50".',
	},
	{
		id: 'long_bow',
		category: 'Missile Weapons',
		name: 'Long Bow',
		iconUrl: 'https://api.iconify.design/mdi:bow-arrow.svg',
		fumbleRange: '1-5',
		primaryCritical: 'Puncture',
		secondaryCritical: '—',
		baseRange: '100*',
		weightLb: 3,
		notes: 'Load(1), or Reload(O) at -35 to OB',
	},
	{
		id: 'short_bow',
		category: 'Missile Weapons',
		name: 'Short Bow',
		iconUrl: 'https://api.iconify.design/mdi:bow-arrow.svg',
		fumbleRange: '1-4',
		primaryCritical: 'Puncture',
		secondaryCritical: '—',
		baseRange: '60*',
		weightLb: 2,
		notes: 'Load(1), or Reload(A) at -10 to OB',
	},
	{
		id: 'sling',
		category: 'Missile Weapons',
		name: 'Sling',
		iconUrl: 'https://api.iconify.design/mdi:slingshot.svg',
		fumbleRange: '1-6',
		primaryCritical: 'Crush(D)',
		secondaryCritical: '—',
		baseRange: '50*',
		weightLb: 0.5,
		notes: 'Load(1), can use with a shield',
	},
];

export default weapons;
